services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coalition-test-app
    volumes:
      - .:/var/www
    ports:
      - 9000:9000
    networks:
      - coalition

  webserver:
    image: nginx:stable-alpine
    container_name: coalition-test-nginx
    ports:
      - 8084:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - coalition

networks:
  coalition:
    driver: bridge
